# Voronoi Diagram Grapher

How to use:
`./voronoi_gen [SCREEN WIDTH] [SCREEN HEIGHT] [NUMBER OF CENTERS] [SHOW CENTERS] [CENTER MARK RADIUS]`

Examples:
`./voronoi_gen 500 500 15 0 0`
will open a 500x500 screen and graph voronoi diagram generated by randomly placed 15 centers, won't show where the centers are. 

`./voronoi_gen 500 500 15 1 5`
will open a 500x500 screen and graph voronoi diagram generated by randomly placed 15 centers, will show where the centers are with circles with 5 radius. 
